apiVersion: garden.io/v2
kind: Project
name: vote-modules
environments:
  - name: local
    variables:
      baseHostname: vote.local.demo.garden
  - name: remote
    variables:
      baseHostname: ${project.name}-testing-${var.userId}.dev-1.sys.garden
providers:
  - name: local-kubernetes
    environments: [local]
  - name: kubernetes
    environments: [remote]
    # Replace the below values as appropriate
    context: gke_garden-ci_europe-west1-b_core-ci
    namespace: ${project.name}-testing-${var.userId}
    defaultHostname: ${var.baseHostname}
    buildMode: kaniko
    deploymentRegistry:
      hostname: eu.gcr.io    # <- set this according to the region your cluster runs in
      namespace: garden-ci   # <- set this to the project ID of the target cluster
    imagePullSecrets:
      # Make sure this matches the name and namespace of the imagePullSecret you've created
      # to authenticate with your registry (if needed)
      - name: gcr-config
        namespace: default
      - name: dockerhub
        namespace: default
variables:
  userId: ${local.username}
  postgres-database: postgres
  # Only use for testing!
  postgres-username: postgres
  postgres-password: test-password
