/*
 * Copyright (C) 2018-2025 Garden Technologies, Inc. <info@garden.io>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import peggy from "peggy"

// This file is just a placeholder to make TypeScript happy
// The actual parser is generated by the build script
// It will be placed in the build outputs and then actually run from there
export const parse: peggy.Parser["parse"] = () => {}
