root: ./docs/

structure:
  readme: welcome.md
  summary: README.md

redirects:
  installation: ./getting-started/1-installation.md
  quick-start: ./getting-started/0-introduction.md
  basics/installation: ./getting-started/1-installation.md
  stack-graph: ./basics/stack-graph.md
  troubleshooting: ./misc/troubleshooting.md
  examples/demo-project: ./example-projects/demo-project.md
  examples/tls-project: ./example-projects/tls-project.md
  examples/using-garden-in-ci: ./guides/using-garden-in-ci.md
  guides/using-remote-sources: ./advanced/using-remote-sources.md
  guides/cert-manager-integration: ./advanced/cert-manager-integration.md
  guides/terraform: ./advanced/terraform.md
  providers/conftest-container: ./reference/providers/conftest-container.md
  providers/conftest-kubernetes: ./reference/providers/conftest-kubernetes.md
  providers/conftest: ./reference/providers/conftest.md
  providers/hadolint: ./reference/providers/hadolint.md
  providers/kubernetes: ./reference/providers/kubernetes.md
  providers/local-kubernetes: ./reference/providers/local-kubernetes.md
  providers/maven-container: ./reference/providers/maven-container.md
  providers/openfaas: ./reference/providers/openfaas.md
  providers/terraform: ./reference/providers/terraform.md
  module-types/conftest: ./reference/module-types/conftest.md
  module-types/container: ./reference/module-types/container.md
  module-types/exec: ./reference/module-types/exec.md
  module-types/hadolint: ./reference/module-types/hadolint.md
  module-types/helm: ./reference/module-types/helm.md
  module-types/kubernetes: ./reference/module-types/kubernetes.md
  module-types/maven-container: ./reference/module-types/maven-container.md
  module-types/openfaas: ./reference/module-types/openfaas.md
  module-types/persistentvolumeclaim: ./reference/module-types/persistentvolumeclaim.md
  module-types/terraform: ./reference/module-types/terraform.md
  # Redirects after docs restructure (https://github.com/garden-io/garden/pull/3467)
  advanced/terraform: ./terraform-plugin/about.md
  advanced/pulumi: ./pulumi-plugin/about.md
  getting-started/1-installation.md: ./guides/installation.md
  basics/5-min-quickstart: ./basics/quickstart.md
  guides/remote-kubernetes: ./k8s-plugins/about.md
