apiVersion: garden.io/v1
kind: Project
name: garden-core
defaultEnvironment: testing
modules:
  include:
    - "*.garden.yml"
environments:
  - name: testing
  - name: local
    variables:
      show-log: true
providers:
  - name: kubernetes
    environments: [ testing ]
    context: ci-context
    namespace: e2e-tests
    defaultHostname: dev-1.sys.garden
    buildMode: cluster-buildkit
    setupIngressController: nginx
  - name: local-kubernetes
    environments: [local]
variables:
  timeout: 360
  show-log: false
