apiVersion: garden.io/v2
kind: Project
name: code-synchronization
environments:
  - name: local
  - name: testing
    defaultNamespace: ${var.userId}
providers:
  - name: local-kubernetes
    environments: [local]
  - name: kubernetes
    environments: [testing]
    # Replace the below values as appropriate
    context: ci-context
    namespace: ${project.name}-testing-${var.userId}
    defaultHostname: ${project.name}-testing-${var.userId}.dev.example.com
    deploymentRegistry:
      hostname: index.docker.io # <- set this to your registry hostname
      namespace: gardenci # <- typically your organization name, project ID etc.
    imagePullSecrets:
      # Make sure this matches the name and namespace of the imagePullSecret you've created
      # to authenticate with your registry (if needed)
      - name: regcred
        namespace: default
variables:
  userId: ${kebabCase(local.username)}
