apiVersion: garden.io/v1
kind: Project
name: istio-example
environments:
  - name: local
providers:
  - name: local-kubernetes
    setupIngressController: null
    namespace: 
      name: istio-garden-example
      labels: 
        istio-injection: enabled
