apiVersion: garden.io/v2
kind: Project
name: istio-example
environments:
  - name: local
providers:
  - name: local-kubernetes
    setupIngressController: false
    namespace:
      name: istio-garden-example
      labels:
        istio-injection: enabled
