apiVersion: garden.io/v2
kind: Project
name: ephemeral-cluster-demo
environments:
  - name: remote
providers:
  - name: ephemeral-kubernetes
    environments: [remote]
variables:
  userId: ${kebabCase(local.username)}

