apiVersion: garden.io/v2
kind: Project
name: terraform-gke

defaultEnvironment: dev

environments:
  - name: dev
    defaultNamespace: ${project.name}-${variables.userId}
  - name: prod
    defaultNamespace: ${project.name}
    production: true

variables:
  # change these values to your own
  username: worldofgeese
  gcpProjectId: devrel-348008
  gcpRegion: europe-north1
  registryHostname: docker.io
  registryNamespace: worldofgeese
  terraformInitRoot: "./terraform/"
  userId: ${kebabCase(local.username)}
providers:
  - name: terraform
    # This must be set to indicate that there is a stack in the terraform project folder.
    initRoot: "${var.terraformInitRoot}"
    autoApply: true
    # You can either uncomment and replace these with your own values, or provide the values in a
    # terraform.tfvars file in the project root.
    # variables:
    #   gcp_project_id: garden-gke-tf-${var.userId}
    #   gcp_region: europe-west1
    allowDestroy: true
    # You can either uncomment and replace these with your own values, or provide the values in a
    # terraform.tfvars file in the project root.
    variables:
      project_id: ${var.gcpProjectId}
      region: ${var.gcpRegion}

  - name: kubernetes
    kubeconfig: ${var.terraformInitRoot}/${providers.terraform.outputs.kubeconfig_path}
    context: ${providers.terraform.outputs.cluster_name}
    # any hostname that points to your cluster's ingress controller
    defaultHostname: ${var.userId}-gke.dev-1.sys.garden
    # Replace the below values as appropriate
    deploymentRegistry:
      hostname: ${variables.registryHostname}
      namespace: ${variables.registryNamespace}
