apiVersion: garden.io/v2
kind: Project
name: local-exec
environments:
  - name: local
providers:
  # Note: the exec provider is loaded by default
  - name: exec
    initScript: "echo hello ${local.username}, this is a provider output message"
  - name: container
    dependencies: [exec]
  - name: local-kubernetes
