#!/usr/bin/env ts-node

/**
 * Helper script for parsing the JSONL log files generated by the Garden CLI in .garden/logs
 */

import * as jsonl from "node-jsonl"
import { resolve } from "path"

async function convert(path: string) {
  const absPath = resolve(process.cwd(), path)
  const rl = jsonl.readlines(absPath)

  while (true) {
    const { value, done } = await rl.next()
    if (done) {
      break
    }
    console.log(`[${value.timestamp}] ${value.msg}`)
  }
}

const args = process.argv.slice(2)
const filename = args[0]

if (require.main === module) {
  convert(filename).catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
