#!/usr/bin/env -S node --import ./scripts/register-hook.js
/*
 * Copyright (C) 2018-2025 Garden Technologies, Inc. <info@garden.io>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/**
 * Helper script for parsing the JSONL log files generated by the Garden CLI in .garden/logs
 */

import * as jsonl from "node-jsonl"
import * as url from "node:url"
import { resolve } from "path"

async function convert(path: string) {
  const absPath = resolve(process.cwd(), path)
  const rl = jsonl.readlines(absPath)

  while (true) {
    const { value, done } = <any>await rl.next()
    if (done) {
      break
    }
    console.log(`[${value.timestamp}] ${value.msg}`)
    if (value.errorDetail) {
      console.log(`[Error detail]: ${value.errorDetail}`)
    }
  }
}

const args = process.argv.slice(2)
const filename = args[0]

const modulePath = url.fileURLToPath(import.meta.url)
if (process.argv[1] === modulePath) {
  convert(filename).catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
