---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: vote-helm-default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    path: postgres
    targetRevision: 12.1.2
    chart: postgresql
    helm:
      version: v3
      values: |
        fullnameOverride: postgres
        auth:
          # This should of course not be used in production
          postgresPassword: postgres
        image:
          repository: bitnamilegacy/postgresql
