/*
 * Copyright (C) 2018 Garden Technologies, Inc. <info@garden.io>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import * as Joi from "joi"
import {
  joiIdentifier,
  validate,
} from "../../config/common"
import {
  GardenPlugin,
  Provider,
} from "../../types/plugin/plugin"
import {
  ProviderConfig,
  providerConfigBase,
} from "../../config/project"

import {
  configureEnvironment,
  deleteConfig,
  destroyEnvironment,
  deleteService,
  execInService,
  getConfig,
  getEnvironmentStatus,
  getServiceLogs,
  getServiceOutputs,
  getTestResult,
  setConfig,
  testModule,
  getLoginStatus,
  login,
  logout,
  runModule,
} from "./actions"
import { deployContainerService, getContainerServiceStatus } from "./deployment"
import { helmHandlers } from "./helm"

export const name = "kubernetes"

export interface KubernetesConfig extends ProviderConfig {
  context: string
  ingressHostname: string
  ingressPort: number
  ingressClass: string
  forceSsl: boolean
  namespace?: string
  defaultUsername?: string
}

export interface KubernetesProvider extends Provider<KubernetesConfig> { }

const kubernetesConfigBase = providerConfigBase
  .keys({
    context: Joi.string()
      .required()
      .description("The kubectl context to use to connect to the Kubernetes cluster."),
    ingressHostname: Joi.string()
      .hostname()
      .required()
      .description("The external hostname of the cluster's ingress controller."),
    defaultUsername: joiIdentifier()
      .description("Set a default username (used for namespacing within a cluster)."),
    namespace: Joi.string()
      .description(
        "Specify which namespace to deploy services to (auto-generated by default). " +
        "Note that the framework generates other namespaces as well with this name as a prefix.",
    ),
  })

const configSchema = kubernetesConfigBase
  .keys({
    ingressPort: Joi.number()
      .default(80)
      .description("The external port of the cluster's ingress controller."),
    ingressClass: Joi.string()
      .description("The ingress class to use on configured Ingresses when deploying services."),
    forceSsl: Joi.boolean()
      .default(true)
      .description("Whether to force use of SSL in configured Ingresses when deploying services."),
    _system: Joi.any().meta({ internal: true }),
  })

export function gardenPlugin({ config }: { config: KubernetesConfig }): GardenPlugin {
  config = validate(config, configSchema, { context: "kubernetes provider config" })

  return {
    config,
    actions: {
      getEnvironmentStatus,
      configureEnvironment,
      destroyEnvironment,
      getConfig,
      setConfig,
      deleteConfig,
      getLoginStatus,
      login,
      logout,
    },
    moduleActions: {
      container: {
        getServiceStatus: getContainerServiceStatus,
        deployService: deployContainerService,
        deleteService,
        getServiceOutputs,
        execInService,
        runModule,
        testModule,
        getTestResult,
        getServiceLogs,
      },
      helm: helmHandlers,
    },
  }
}
