apiVersion: garden.io/v1
kind: Project
name: gke
environments:
  - name: gke-kaniko
    variables:
      buildMode: kaniko
  - name: gke-buildkit
    variables:
      buildMode: cluster-buildkit
providers:
  - name: kubernetes
    # Replace these values as appropriate
    # > the kube context of the cluster
    context: gke_garden-ci_europe-west1-b_core-ci
    # > the namespace to deploy to in the cluster
    namespace: gke-testing-${var.userId}
    # > any hostname that points to your cluster's ingress controller
    defaultHostname: ${var.userId}-gke.dev-1.sys.garden
    buildMode: ${var.buildMode} # <- set differently in each environment above
    deploymentRegistry:
      # Replace these values as appropriate
      hostname: eu.gcr.io # <- set this according to the region your cluster runs in
      namespace: garden-ci # <- set this to the project ID of the target cluster
    imagePullSecrets:
      # Make sure this matches the name and namespace of the imagePullSecret you've created
      - name: gcr-config
        namespace: default
      - name: dockerhub
        namespace: default
variables:
  userId: ${kebabCase(local.username)}
