apiVersion: garden.io/v1
kind: Project
name: gke
environments:
  - name: gke
  - name: gke-buildkit
    variables:
      buildMode: cluster-buildkit
providers:
  - name: kubernetes
    # Replace these values as appropriate
    # > the kube context of the cluster
    context: ci-context
    # > the namespace to deploy to in the cluster
    namespace: gke-testing-${var.userId}
    # > any hostname that points to your cluster's ingress controller
    defaultHostname: ${var.userId}-gke.dev.example.com
    buildMode: ${var.buildMode} # <- set differently in each environment above
    deploymentRegistry:
      # Replace these values as appropriate
      hostname: eu.gcr.io # <- set this to your registry hostname according to the region your cluster runs in
      namespace: gardenci # <- typically your organization name, project ID etc.
    imagePullSecrets:
      # Make sure this matches the name and namespace of the imagePullSecret you've created
      - name: regcred
        namespace: default
variables:
  userId: ${kebabCase(local.username)}
