apiVersion: garden.io/v2
kind: Project
name: variables
variables:
  # This variable is referenced in the module configs, and overridden in the local project below
  service-replicas: 3
environments:
  - name: local
    variables:
      # We only want one replica of each service when developing locally
      service-replicas: 1
  - name: testing
providers:
  - name: local-kubernetes
    environments: [local]
